# Website settings
url: "/" # the base hostname & protocol for your site (e.g. http://example.com)
baseurl: "/Horizon" # the subpath of your site (e.g. /blog)
title: "Horizon template" # the name of your site

# User settings
name: Horizon Template
picture: picture.jpg
background-video: background.mp4
background-image: background.jpg
about: Lorem Ipsum
email: email@example.com
github: username-github
gitlab: username-gitlab
linkedin: username-linkedin
twitter: username-twitter
